[core]
workspace_base = "" # path to the workspace, pass files to the agent
cache_dir = ""
file_store_path = ""
save_trajectory_path = ""

run_as_openhands = false # use root in sandbox since we are using rootless, otherwise set sandbox.user_id
runtime = "docker"  # overridden by --runtime flag

# Modal credentials
modal_api_token_id = "ak-SZFkxukYEnRxhjxMUOuGJs"
modal_api_token_secret = "as-pPYEplZCfEqQYhCqL2ICIf"


[llm]
model = ""
# api_key = "" # use environment LLM_API_KEY instead for security
max_output_tokens = 2048

[sandbox]
# user_id = 1000
runtime_container_image = "us-east1-docker.pkg.dev/jailbreak-defense/claude-reversing/claude-reversing:latest"
docker_runtime_kwargs = {auto_remove = true}
runtime_binding_address = "127.0.0.1"
